### ISSUE TITLE
Wants a "blobs" path, has a "manifests" path

### ISSUE THREAD

**Issue by malthe** [jpetazzo/registrish#3]
I'm using:
```bash
$ export IMAGE=gcr.io/google-samples/node-hello
$ export TAG=1.0
```
Uploading to S3 buckets gets me:
```
upload: v2/gcr.io/google-samples/node-hello/manifests/sha256:<sha> to 
    s3://<bucket>/v2/gcr.io/google-samples/node-hello/manifests/sha256:<sha> 
```
(Where <sha> is "f5ba02e2b2cd2d9476c67fd0b5ce889f2a5263a3de81d4839b0930c4e7a10eb3".)

But both Kubernetes and [nerdctl](https://github.com/containerd/nerdctl) wants to pull:
```
https://<bucket>.<endpoint-url>/v2/gcr.io/google-samples/node-hello/blobs/sha256:<sha>
```
That is, "blobs" instead of "manifests".

Is that `skopeo` doing something wrong?

**Comment by jpetazzo** [comment]
Hi!

Skopeo is alright, but registrish doesn't handle the old v1 manifest format (which `gcr.io/google-samples/node-hello:1.0` is using).

In 4dcb001 I add a test to set the content-type to the v1 manifest string if there is no `.mediaType` field in the manifest. It seems to work in my local test, but it's very hackish. Try it out and let me know if that helps!

**Comment by malthe** [comment]
@jpetazzo I ended up using [nerdctl save](https://github.com/containerd/nerdctl#whale-nerdctl-save) and reworking your script to match its output:

https://github.com/malthe/static-container-registry
